@startuml
title OAuth 기반 로그인

actor Client
participant OAuth2LoginFilter
participant CustomOAuth2UserService
participant AuthRepository
participant AuthRepository
participant SecurityContext

Client -> OAuth2LoginFilter : GET /oauth2/authorization/kakao
OAuth2LoginFilter -> CustomOAuth2UserService : loadUser(oAuth2UserRequest)
CustomOAuth2UserService -> AuthRepository : findByProviderAndProviderUserId()
alt 존재함
  AuthRepository --> CustomOAuth2UserService : Auth
  CustomOAuth2UserService -> SecurityContext : saveAuthentication(Auth)
  OAuth2LoginFilter --> Client : 로그인 성공
else 최초 로그인
  AuthRepository --> CustomOAuth2UserService : null
  CustomOAuth2UserService --> OAuth2LoginFilter : 인증은 안 됨
  OAuth2LoginFilter --> Client : redirect to \nOauth Signup Page(Signup JWT)
end
@enduml