@startuml
title updatePassword

actor User
participant AuthController
participant AuthService
participant AuthRepository
entity Auth
participant Password
participant JWTProvider

User -> AuthController : PATCH /auth/password\n(Authorization: Bearer Token, newPw)

AuthController -> AuthService : changePassword(token, newPw)

AuthService -> JWTProvider : parsePasswordChangeToken(token)
JWTProvider --> AuthService : memberId

AuthService -> AuthRepository : findByMemberId(memberId)
AuthRepository --> AuthService : Auth

AuthService -> Auth : updatePassword(newPw)

AuthService -> AuthRepository : save(Auth)
AuthService --> AuthController : void
AuthController --> User : HTTP 200 OK

@enduml