@startuml
title 이메일 인증 코드 확인

actor User
participant AuthController
participant AuthService
participant PendingAuthRepository
participant JWTProvider

User -> AuthController : GET /auth/verify?code=verificationCode
AuthController -> AuthService : verifyEmail(code)

AuthService -> PendingAuthRepository : findByCode(code)
PendingAuthRepository --> AuthService : email

AuthService -> JWTProvider : issueSignupToken(email)
JWTProvider --> AuthService : SignupToken

AuthService --> User : redirect to \nEmail Signup Page(SignupToken)
@enduml