@startuml
title verifyCurrentPassword

actor User
participant AuthController
participant AuthService
participant AuthRepository
entity Auth
participant Password
participant JWTProvider
participant ExceptionHandler as "GlobalExceptionHandler\n(@ControllerAdvice)"

User -> AuthController : POST /auth/password/verify\n(currentPw)

AuthController -> AuthService : verifyCurrentPassword(memberId, currentPw)

AuthService -> AuthRepository : findByMemberId(memberId)
AuthRepository --> AuthService : Auth

AuthService -> Auth : verifyPassword(currentPw)
Auth --> AuthService : token(memberId)
AuthService --> AuthController : token(memberId)
AuthController --> User : HTTP 200 OK \ntoken(memberId)


alt 위에서 끝 \n아래는분리해야하는 것들
Auth --> User : HTTP 400 Bad Request (throw InvalidPasswordException)
activate Auth
Auth -> Password : matches(currentPw)
Password -> Auth : true 또는 false

alt 비밀번호 일치
  deactivate Auth
  AuthService -> JWTProvider : issuePasswordChangeToken(memberId)
  JWTProvider --> AuthService : token
  AuthService --> AuthController : token
  AuthController --> User : HTTP 200 OK (token)

else 비밀번호 불일치
  Auth --> User : HTTP 400 Bad Request (throw InvalidPasswordException)
end
end
@enduml