@startuml
package "board" {
    entity Board <<Aggregate Root>> {
        +Long boardId
        +String boardName
        +Creator creator
        +createdAt dateTime
        --
        +create(String boardName, Long creatorId) : Board
        +delete()
        +verifyBoardName(String boardName)
    }

    class Creator <<Value Object>> {
        +Long : memberId
     }
     
     Board -- Creator
}
@enduml
