@startuml
package "board" {
    entity Board <<Aggregate Root>> {
        +Long boardId
        +String boardName
        +createdAt dateTime
        --
        +create(String boardName) : Board
        +delete()
        +verifyBoardName(String boardName)
    }
}
@enduml
