spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
  jpa:
    show-sql: false
#    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      jakarta.persistence.schema-generation.database.action: create  # create-only
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        hbm2ddl.halt_on_error: false  # ignore harmless DDL errors if any

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

#logging:
#  level:
#    org.hibernate.SQL: debug                 # SQL 템플릿
#    org.hibernate.orm.jdbc.bind: trace       # 바인딩된 파라미터 값
#    org.hibernate.orm.jdbc.extract: trace

logging:
  level:
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.springframework.transaction.support: DEBUG
    org.hibernate.engine.transaction.internal.TransactionImpl: DEBUG

decorator:
  datasource:
    datasource-proxy:
      enable-logging: true
      multiline: true
      query.log-level: DEBUG
