@startuml
title createBoard

actor Client
participant BoardController
participant BoardCommandService
participant BoardCommandRepository
Entity Board
participant DomainEventPublisher


Client -> BoardController : POST /board \n(boardCreateRequest)

BoardController -> BoardCommandService : createBoard \n(boardCreateCommand, userId)

BoardCommandService -> Board : Board.create(boardCreateCommand)

activate Board
Board --> BoardCommandService : Board
deactivate Board

BoardCommandService -> BoardCommandRepository : save(board)

BoardCommandService -> DomainEventPublisher : publish(BoardCreatedEvent)

BoardCommandService --> BoardController : BoardId
BoardController --> Client : HTTP 201 + BoardId
@enduml