@startuml
actor User
participant BoardController
participant BoardQueryService
participant BoardQueryRepository

User -> BoardController : GET /boards? \npage={page}&size={size}&searchType={type}&keyword={kw}
BoardController -> BoardQueryService : getBoards(SearchCondition searchCondition)
note right of BoardController
<b>SearchCondition</b>
* int page
* int size
* String searchType \t//title
* String keyword
end note

BoardQueryService -> BoardQueryRepository : findBoards(searchCondition)
BoardQueryRepository --> BoardQueryService : List <Board>

BoardQueryService --> BoardController : BoardListResult
note left of BoardQueryService
<b>BoardListResult</b>
end note

BoardController --> User : HTTP 200 OK + BoardListResponse
note right of User
<b>BoardListResponse</b>
end note
@enduml