@startuml updateNicknameSeq
title Update Nickname

actor User
participant MemberController
participant MemberCommandService
participant MemberCommandRepository
entity      Member
participant DomainEventPublisher #skyblue

User -> MemberController : PATCH /users/me (nickname)
MemberController -> MemberCommandService : updateNickname(memberId, nickname)
MemberCommandService -> MemberCommandRepository : findById(memberId)
activate Member
MemberCommandRepository --> MemberCommandService : Member

MemberCommandService -> Member : updateNickname(newNickname)

alt 닉네임이 유효하고 중복 아님
Member --> MemberCommandService : 완료
MemberCommandService -> DomainEventPublisher : NicknameUpdatedEvent
deactivate Member
MemberCommandService -> MemberCommandRepository : save(Member)
MemberCommandService --> MemberController : OK
MemberController --> User : 200 OK

else 닉네임이 유효하지 않거나 중복
Member --> User : 400 Bad Request

end

@enduml
